# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Direct Talk
description: > # this means to ignore newlines until "baseurl:"
  Fique por dentro do que a DirectTalk está usando em seus ambientes e quais as últimas tecnologias que estamos implantando!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://directtalk.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# Link para arquivos estaticos
staticfiles: "/assets"

